### ISSUE TITLE
Incorrect read from data sources

### ISSUE THREAD

**Issue by Mintaka** [Mintaka/mypyladies_sqlite#4]
https://github.com/Mintaka/mypyladies_sqlite/blob/f5b4cc8c016340ad62d8fd2ae929c3591893a3af/process_meteo_data.py#L69

It si not right way how to get data from that type of data sources.

Main goal: Read data from that files correctly.
Method which solve where to start read data can be build on presence data header line.

**Comment by cinkim** [comment]
Jestli tomu rozumim, tak chces cist csv az od radky 5. Kde mas ale jistotu, ze se nezmeni struktura csv? Me to prijde takto logicke.

**Comment by Mintaka** [comment]
Nedá se spolehnout, že to bude na konkrétním řádku, v různých datových souborech data začínají na jiných řádcích, takže je třeba zvolit jiný způsob jak zjistit kde začínají data.

**Comment by Mintaka** [comment]
Vyřešeno kódem: https://github.com/Mintaka/mypyladies_sqlite/pull/27
